// AUTH
export const LOGIN_START    = "LOGINSTART"
export const LOGIN_SUCCESS  = "LOGINSUCCESS"
export const LOGIN_FAILED   = "LOGINFAILED"
export const LOGIN_END      = "LOGINEND"

export const REGISTER_START     = "REGISTERSTART"
export const REGISTER_SUCCESS   = "REGISTERSUCCESS"
export const REGISTER_FAILED    = "REGISTERFAILED"
export const REGISTER_END       = "REGISTEREND"
export const REGISTER_INIT      = "REGISTERINIT"
/** Reset Password actions */
export const RESET_START      = "RESETPWSTART"
export const RESET_SUCCESS    = "RESETPWSUCCESS"
export const RESET_FAILED     = "RESETPWFAILED"
export const RESET_END        = "RESETPWEND"
export const RESET_INIT       = "RESETPWINIT"

/** Send Email Reset Password */
export const SENDEMAILRESET_START   = "SENDEMAILRESETSTART"
export const SENDEMAILRESET_SUCCESS = "SENDEMAILRESETSUCCESS"
export const SENDEMAILRESET_FAILED   = "SENDEMAILRESETFAILED"
export const SENDEMAILRESET_END   = "SENDEMAILRESETEND"
export const SENDEMAILRESET_INIT   = "SENDEMAILRESETSTART"
