export const IMG_TEXTURE            = require('../assets/images/background.png')
export const IMG_BG_DOT             = require('../assets/images/bg-dot.png')
export const IMG_BRAIN              = require('../assets/images/brain.png')
export const IMG_BRAIN_WHITE        = require('../assets/images/brain-white.png')
export const IMG_ZOOMIN             = require('../assets/images/zoom-in.png')
export const IMG_ZOOMOUT            = require('../assets/images/zoom-out.png')
export const IMG_BACK               = require('../assets/images/backbtn.png')
export const IMG_DROPDOWN           = require('../assets/images/dropdownbtn.png')
export const IMG_CHECKMARK          = require('../assets/images/checkmark.png')
export const IMG_LANDMARK           = require('../assets/images/landmark.png')
export const IMG_LOADING            = require('../assets/images/ajax-loader.gif')
export const IMG_BG_MAP             = require('../assets/images/bg-map.png')
export const IMG_SAMPLE_AVATAR      = require('../assets/images/sample_avatar.png')
export const IMG_BG_REVIEW          = require('../assets/images/bg-review.png')
export const IMG_LEARNING_ROUTE     = require('../assets/images/learning_routine.png')
export const IMG_BRAIN_COUNTDOWN    = require('../assets/images/passage-of-time.png')

export const IMG_ICON_GOOGLE        = require('../assets/images/search@2x.png')
export const IMG_ICON_FACEBOOK      = require('../assets/images/facebook@2x.png')
export const IMG_ICON_INSTAGRAM     = require('../assets/images/instagram@2x.png')
export const IMG_ICON_TWITTER       = require('../assets/images/twitter@2x.png')
export const IMG_ICON_PROFILE       = require('../assets/images/profile.png')
export const IMG_ICON_BACKBTN       = require('../assets/images/icon-back1.png')
export const IMG_ICON_DOT_CHECK     = require('../assets/images/dot-checked.png')
export const IMG_ICON_DOT_UNCHECK   = require('../assets/images/dot-unchecked.png')

// Maps
export const IMG_MAP_1              = require('../assets/images/maps/1.png')
export const IMG_MAP_2              = require('../assets/images/maps/2.png')
export const IMG_MAP_3              = require('../assets/images/maps/3.png')
export const IMG_MAP_4              = require('../assets/images/maps/4.png')
export const IMG_MAP_5              = require('../assets/images/maps/5.png')
export const IMG_MAP_6              = require('../assets/images/maps/6.png')
export const IMG_MAP_7              = require('../assets/images/maps/7.png')
export const IMG_MAP_8              = require('../assets/images/maps/8.png')

// Guide
export const IMG_GUIDE_BRAINSTORM_1 = require('../assets/images/guide/brainstorm/1.png')
export const IMG_GUIDE_BRAINSTORM_2 = require('../assets/images/guide/brainstorm/2.png')
export const IMG_GUIDE_BRAINSTORM_3 = require('../assets/images/guide/brainstorm/3.png')
export const IMG_GUIDE_BRAINSTORM_4 = require('../assets/images/guide/brainstorm/4.png')

export const IMG_GUIDE_WORDGLOB_1   = require('../assets/images/guide/wordglob/1.png')
export const IMG_GUIDE_WORDGLOB_2   = require('../assets/images/guide/wordglob/2.png')
export const IMG_GUIDE_WORDGLOB_3   = require('../assets/images/guide/wordglob/3.png')
export const IMG_GUIDE_WORDGLOB_4   = require('../assets/images/guide/wordglob/4.png')
export const IMG_GUIDE_WORDGLOB_5   = require('../assets/images/guide/wordglob/5.png')
export const IMG_GUIDE_WORDGLOB_6   = require('../assets/images/guide/wordglob/6.png')
export const IMG_GUIDE_WORDGLOB_7   = require('../assets/images/guide/wordglob/7.png')
export const IMG_GUIDE_WORDGLOB_8   = require('../assets/images/guide/wordglob/8.png')
export const IMG_GUIDE_WORDGLOB_9   = require('../assets/images/guide/wordglob/9.png')
export const IMG_GUIDE_WORDGLOB_10  = require('../assets/images/guide/wordglob/10.png')

export const IMG_GUIDE_REVIEW_1     = require('../assets/images/guide/review/1.png')
export const IMG_GUIDE_REVIEW_2     = require('../assets/images/guide/review/2.png')
export const IMG_GUIDE_REVIEW_3     = require('../assets/images/guide/review/3.png')
export const IMG_GUIDE_REVIEW_4     = require('../assets/images/guide/review/4.png')
