export const IMG_TEXTURE        = require('../assets/images/background.png')
export const IMG_BG_DOT         = require('../assets/images/bg-dot.png')
export const IMG_BRAIN          = require('../assets/images/brain.png')
export const IMG_BRAIN_WHITE    = require('../assets/images/brain-white.png')
export const IMG_ZOOMIN         = require('../assets/images/zoom-in.png')
export const IMG_ZOOMOUT        = require('../assets/images/zoom-out.png')
export const IMG_BACK           = require('../assets/images/backbtn.png')
export const IMG_DROPDOWN       = require('../assets/images/dropdownbtn.png')
export const IMG_CHECKMARK      = require('../assets/images/checkmark.png')
export const IMG_LANDMARK       = require('../assets/images/landmark.png')
export const IMG_LOADING        = require('../assets/images/ajax-loader.gif')

export const IMG_ICON_GOOGLE    = require('../assets/images/search@2x.png')
export const IMG_ICON_FACEBOOK  = require('../assets/images/facebook@2x.png')
export const IMG_ICON_INSTAGRAM = require('../assets/images/instagram@2x.png')
export const IMG_ICON_TWITTER   = require('../assets/images/twitter@2x.png')

